language: java
jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: "meronbrouwer-github"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

after_success:
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
  - mvn jacoco:report coveralls:report
  - mvn javadoc:javadoc
  - mvn install:install-file -Dfile=target/yaeger-shadyjar.jar -DgroupId=nl.han.ica -DartifactId=yaeger-shadyjar -Dversion=1.0.0 -Dpackaging=jar -DgeneratePom=true
  - mkdir -p target/site/apidocs/nl/han/ica/yaeger-shadyjar/1.0.0
  - cp /home/travis/.m2/repository/nl/han/ica/yaeger-shadyjar/1.0.0/yaeger-shadyjar-1.0.0.pom target/site/apidocs/nl/han/ica/yaeger-shadyjar/1.0.0/
  - mv target/yaeger-shadyjar.jar target/site/apidocs/nl/han/ica/yaeger/1.0.0/yaeger-shadyjar-1.0.0.jar

deploy:
    provider: pages
    local-dir: target/site/apidocs
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: false
    on:
      branch: master